name: "🚨 Incident report"
description: Report a bug or unexpected behavior in a PowerShell script/module
labels: [incident]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Before submitting**, please remove or anonymize any personal/sensitive data from logs.
        This includes user IDs, file paths, and any other sensitive information.
        If you need to share sensitive data, consider using a direct message to [dev@kmarflow.com](mailto:dev@kmarflow.com).

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what went wrong. Include error messages or unexpected behavior.
      placeholder: "When running the script, I get an error..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: "I expected the script to..."
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Tell us how to reproduce the issue.
      placeholder: |
        1. Open PowerShell
        2. Run the script with these parameters
        3. Observe the error
    validations:
      required: true

  - type: input
    id: ps-version
    attributes:
      label: PowerShell version
      description: Run `$PSVersionTable.PSVersion` in PowerShell and paste the result
      placeholder: "e.g., 5.1.22621.2506 or 7.4.1"
    validations:
      required: true

  - type: input
    id: windows-version
    attributes:
      label: Windows version (optional)
      placeholder: "e.g., Windows 11 Pro 23H2, Build 22631.3593"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Attach logs or error output (please anonymize them first)
    validations:
      required: true

