name: Auto-manage Project Items

on:
  issues:
    types: [opened, labeled, reopened, assigned, closed]

jobs:
  add-to-project:
    if: github.event.action == 'opened' || github.event.action == 'labeled'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read

    steps:
      - name: Add to Project
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}

      - name: Move to Backlog
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
          field-name: Status
          field-value: Backlog

  move-to-in-progress:
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Set Status to In Progress
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
          field-name: Status
          field-value: In Progress

  move-to-shipped:
    if: github.event.action == 'closed'  &&
        contains(github.event.issue.labels.*.name, 'feature-request') &&
        github.event.issue.state_reason != 'not-planned' &&
        github.event.issue.state_reason != 'duplicate'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Set Status to Shipped
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
          field-name: Status
          field-value: Shipped

      - name: Add resolved/released Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: resolved/released

  move-to-resolved-incident:
    if: github.event.action == 'closed' &&
        (! contains(github.event.issue.labels.*.name, 'feature-request')) &&
        github.event.issue.state_reason != 'not-planned' &&
        github.event.issue.state_reason != 'duplicate'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Set Status to Resolved (Incident)
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
          field-name: Status
          field-value: Resolved

      - name: Add resolved/released Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: resolved/released

  move-to-duplicate:
    if: github.event.action == 'closed' &&
        github.event.issue.state_reason == 'duplicate' &&
        contains(github.event.issue.labels.*.name, 'feature-request')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Set Status to Rejected
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
          field-name: Status
          field-value: Rejected

      - name: Add wontfix Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: duplicate

  reopened-handling:
    if: github.event.action == 'reopened'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Remove resolved/released Label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: resolved/released

      - name: Add Reopened Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: reopened

      - name: Move to Backlog
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
          field-name: Status
          field-value: Backlog

      - name: Remove all assignees
        uses: actions-cool/issues-helper@main
        with:
          actions: 'remove-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: '*'

  move-to-rejected:
    if: github.event.action == 'closed' &&
        github.event.issue.state_reason == 'not-planned' &&
        contains(github.event.issue.labels.*.name, 'feature-request')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Set Status to Rejected
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
          field-name: Status
          field-value: Rejected
