name: Auto-add Feature Requests to Project

on:
  issues:
    types: [opened, labeled, reopened]

jobs:
  add-to-project:
    if: github.event.action == 'opened' || github.event.action == 'labeled' || github.event.action == 'reopened'
    runs-on: ubuntu-latest
    permissions:
      contents: read    # required by the action
      issues: read
      id-token: write
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          labeled: enhancement
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}


  move-to-in-progress:
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      id-token: write
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          field: Status
          value: In Progress
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}

  move-to-shipped:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      id-token: write
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/halatsWol/projects/3
          field: Status
          value: Shipped
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}